// SPDX-License-Identifier: AGPL-3.0-or-later
import fs from 'node:fs';
import path from 'node:path';
import { writeDefaultConfig, loadConfig } from './config.mjs';
import { DEFAULT_CONFIG } from './defaults.mjs';
import { exists, writeJson, writeText } from './lib/fs.mjs';
import { emptyWaivers } from './waivers.mjs';
import { emptyGeneratedRegistry } from './analyzers/generated.mjs';
import { GREENROOM_BEGIN, GREENROOM_END, RULES_TEXT, SKILL_TEXT, workflowText } from './managed.mjs';

function preflightManagedMarkers(root, agentFiles) {
  for (const rel of agentFiles || []) {
    const file = path.join(root, rel);
    if (!exists(file)) continue;
    const current = fs.readFileSync(file, 'utf8');
    const start = current.indexOf(GREENROOM_BEGIN);
    const end = current.indexOf(GREENROOM_END);
    if ((start >= 0) !== (end >= 0) || (start >= 0 && end < start)) throw new Error(`Malformed Green Room managed markers in ${rel}. Repair the marker pair before re-running init.`);
  }
}

function ensureManagedBlock(file, header = '') {
  let current = exists(file) ? fs.readFileSync(file, 'utf8') : header;
  const start = current.indexOf(GREENROOM_BEGIN);
  const end = current.indexOf(GREENROOM_END);
  if (start >= 0) current = current.slice(0, start).trimEnd() + '\n\n' + RULES_TEXT + current.slice(end + GREENROOM_END.length);
  else current = current.trimEnd() + (current.trim() ? '\n\n' : '') + RULES_TEXT + '\n';
  writeText(file, current);
}

export { workflowText, SKILL_TEXT } from './managed.mjs';

export function initialize(root, { existing = false } = {}) {
  const created = [];
  const updated = [];
  const configExists = exists(path.join(root, '.greenroom.json'));
  const preflightConfig = configExists ? loadConfig(root) : DEFAULT_CONFIG;
  preflightManagedMarkers(root, preflightConfig.generatedAgentFiles);

  if (!configExists) { writeDefaultConfig(root); created.push('.greenroom.json'); }
  const config = loadConfig(root);
  if (!exists(path.join(root, config.registryFile))) {
    writeJson(path.join(root, config.registryFile), { version: 1, responsibilities: {}, components: {} }); created.push(config.registryFile);
  }
  if (!exists(path.join(root, config.waiversFile))) { writeJson(path.join(root, config.waiversFile), emptyWaivers()); created.push(config.waiversFile); }
  if (!exists(path.join(root, config.generatedFile))) { writeJson(path.join(root, config.generatedFile), emptyGeneratedRegistry()); created.push(config.generatedFile); }
  for (const f of config.generatedAgentFiles || []) {
    const target = path.join(root, f); const was = exists(target); const before = was ? fs.readFileSync(target, 'utf8') : null;
    ensureManagedBlock(target, `# ${path.basename(f)}\n`);
    if (!was) created.push(f); else if (fs.readFileSync(target, 'utf8') !== before) updated.push(f);
  }
  const skill = config.managed.skillFile;
  const skillPath = path.join(root, skill);
  if (!exists(skillPath)) { writeText(skillPath, SKILL_TEXT); created.push(skill); }
  else if (config.managed.enforceSkillExact && fs.readFileSync(skillPath, 'utf8') !== SKILL_TEXT) { writeText(skillPath, SKILL_TEXT); updated.push(skill); }

  const workflow = config.managed.workflowFile;
  const workflowPath = path.join(root, workflow);
  const desiredWorkflow = workflowText(config);
  if (!exists(workflowPath)) { writeText(workflowPath, desiredWorkflow); created.push(workflow); }
  else {
    const current = fs.readFileSync(workflowPath, 'utf8');
    if (current.startsWith('# Generated by Green Room.') && current !== desiredWorkflow) { writeText(workflowPath, desiredWorkflow); updated.push(workflow); }
  }
  fs.mkdirSync(path.join(root, '.greenroom'), { recursive: true });
  return { created, updated, existing };
}
