// SPDX-License-Identifier: AGPL-3.0-or-later
export const GREENROOM_BEGIN = '<!-- GREEN-ROOM:BEGIN -->';
export const GREENROOM_END = '<!-- GREEN-ROOM:END -->';

export const RULES_TEXT = `${GREENROOM_BEGIN}
## Green Room Repository Rules

This repository is protected by Green Room.

1. Search for the owning responsibility and canonical implementation before creating a file, component, helper, service, hook, script, style, or adapter.
2. Prefer changing the canonical implementation over creating a parallel implementation. If canonicality is unclear, investigate it instead of guessing.
3. When replacing behavior, migrate production callers and delete the superseded path in the same cleanup transaction.
4. Tests passing does not prove a feature is wired into production. Verify reachability from declared production entrypoints.
5. No single analyzer, textual match, or "unused" report authorizes deletion. Use corroborated evidence, blast-radius mapping, and behavior-preservation checks.
6. Do not add compatibility wrappers, fix/repair scripts, versioned copies, or duplicate components unless a real external compatibility requirement makes them necessary.
7. Generated artifacts are derived state: regenerate them from their declared source instead of hand-editing them into competing truth.
8. Use registered design-system components and tokens before inventing styling primitives. New canonical primitives are architecture decisions, not feature-task shortcuts.
9. Run \`greenroom doctor "<task>"\` before substantial implementation and \`greenroom check\` before declaring work complete.
10. Never re-baseline, weaken policy, rewrite the canonical registry, alter generated-governance declarations, or add a waiver merely to make a feature change pass. Those are human governance actions.

A feature merely working is not sufficient. It must be canonical, production-reachable, and no harder for the next agent to understand.
${GREENROOM_END}`;

export const SKILL_TEXT = `# Green Room Hygiene Skill

Use this procedure for every non-trivial repository change. Green Room exists to keep the repository predictable for humans and coding agents, not merely to make lint output green.

## Before coding
1. Run \`greenroom doctor "<task>"\`.
2. Identify the owning responsibility, canonical implementation, production entrypoints, callers, tests, generated artifacts, design primitives, and known replaced paths.
3. Search for competing implementations and existing utilities before creating anything.
4. Decide whether the task can be completed by changing, consolidating, moving, or deleting existing code. Creation is the last option.
5. Treat provider findings as evidence. One scanner saying "unused" is never enough to delete code.

## During coding
- Change the canonical implementation directly when safe.
- Keep one responsibility owned by one canonical path or explicitly declared set of paths.
- Migrate production callers in the same change; test-only reachability is not production wiring.
- Delete superseded code instead of leaving compatibility debris.
- Do not add fix/final/new/v2 copies to escape understanding existing code.
- Do not create scripts whose purpose is to patch or invoke other scripts unless that orchestration is explicitly owned and allowed by policy.
- Do not hand-edit generated outputs. Regenerate them from their registered sources.
- Do not invent parallel UI primitives or raw design values when the design system already owns the responsibility.
- Prefer one deep, coherent module over chains of shallow wrappers.
- Treat changes to Green Room policy, baseline, waivers, canonical registry, generated registry, or managed guard files as human governance work.

## Cleanup work
Use a Green Room cleanup campaign as a transaction. Progress from detection through corroboration, blast-radius mapping, canonicality, behavior preservation, isolated mutation, verification, and only then ratchet acceptance. Ambiguous deletion stays human-review-required.

## Before completion
1. Run the repository's tests, typecheck, build, and relevant runtime/visual validation where available.
2. Verify new behavior is reachable from the intended production root.
3. Run \`greenroom check\`.
4. If Green Room reports new entropy, fix the code. Do not re-baseline or weaken policy.
5. If a rule truly cannot apply, stop and request a human governance decision.
6. Use \`greenroom cleanup plan\` / \`greenroom cleanup verify\` for bounded cleanup work. Green Room plans and verifies cleanup; it does not blindly rewrite repositories.
`;

export function workflowText(config) {
  return `# Generated by Green Room. Customize policy in .greenroom.json, not this gate.\nname: Green Room\n\non:\n  pull_request:\n  push:\n    branches: [main, master]\n\npermissions:\n  contents: read\n\njobs:\n  entropy-gate:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n        with:\n          fetch-depth: 0\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n      - name: Install Green Room\n        run: ${config.distribution.installCommand}\n      - name: Entropy gate (pull request)\n        if: github.event_name == 'pull_request'\n        env:\n          GREENROOM_COMPARE_REF: origin/\${{ github.base_ref }}\n          GREENROOM_ALLOW_GOVERNANCE_UPDATE: \${{ vars.GREENROOM_ALLOW_GOVERNANCE_UPDATE }}\n        run: ${config.distribution.checkCommand || 'npx greenroom check'}\n      - name: Entropy gate (push)\n        if: github.event_name == 'push'\n        env:\n          GREENROOM_COMPARE_REF: \${{ github.event.before }}\n          GREENROOM_ALLOW_GOVERNANCE_UPDATE: \${{ vars.GREENROOM_ALLOW_GOVERNANCE_UPDATE }}\n        run: ${config.distribution.checkCommand || 'npx greenroom check'}\n`;
}

export function extractManagedBlock(text) {
  const start = text.indexOf(GREENROOM_BEGIN);
  const end = text.indexOf(GREENROOM_END);
  if (start < 0 || end < start) return null;
  return text.slice(start, end + GREENROOM_END.length);
}
